version: "3.7"

networks:
    e_collect_network:
      name: e_collect_network

services:
  database_e_collect:
    container_name: e_collect_database
    image: postgres:14.3
    restart: always
    volumes:
      - e_collect_db:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=e_collect_db
      - POSTGRES_USER=e_collect_dbmanager_2LiyBoLHeHo5yG
      - POSTGRES_PASSWORD=2LiyBoLHeHo5yGfxan8euHGIzEEzIs
      - POSTGRES_HOST_AUTH_METHOD=md5
    networks:
      - e_collect_network
    ports:
      - "5432:5432"

  django_e_collect:
    container_name: e_collect_django
    image: e_collect:1.0
    platform: linux/amd64
    environment:
      - DB_NAME=e_collect_db
      - DB_HOST=e_collect_database
      - DB_PASSWORD=2LiyBoLHeHo5yGfxan8euHGIzEEzIs
      - DB_ENGINE=django.db.backends.postgresql
      - DB_USER=e_collect_dbmanager_2LiyBoLHeHo5yG
      - DB_PORT=5432
      - SECRET_KEY=NYPmGeU11uQ96YQtX9UjOZ_EuAGsuJltGJt5XBrXt0HQhgShCP7KIWlLFgxtZDhl0z4
      - ALLOWED_HOSTS=.localhost,*
      - DEBUG=True
      - SENTRY_DNS=""
      - API_PATH=http://localhost:8080/
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - EMAIL_PASSWORD=''
      - EMAIL_LOGIN=''
      - EMAIL_SMTP=''
      - EMAIL_PORTA=''
      - EMAIL_DESTINO=''
      - FCM_KEY=''
      - GOOGLE_API_KEY=''
      - HORAS_SEM_ATENDIMENTO=19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 12
      - DIAS_DA_SEMANA=0, 1, 2, 3, 4
      - SENHA_PADRAO=123456
    build:
      context: .
      dockerfile: ./DockerfileDev
    networks:
      - e_collect_network
    command: bash -c "python manage.py makemigrations; python manage.py migrate; python manage.py collectstatic; python manage.py runserver 0.0.0.0:8000;"
    volumes:
      - .:/app
      - ../../FastAPI/e_collect:/FastAPI
    ports:
      - "8000:8000"
    depends_on:
      - database_e_collect

volumes:
    e_collect_db:

