[tool.taskipy.settings]
user_vars = true

[tool.pytest.ini_options]
addopts = "--cov=e_collect --cov-report=html --cov-fail-under=90 --doctest-modules --doctest-glob='*.rst' --ignore=core --ignore=docs --ignore=venv --ignore=.venv --ignore=.env"

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
max-line-length = 120
line-length = 120
ignore = "E203, W503"
extend-exclude = '''
(
  ^/core/*
  ^/docs/*
  ^.venv/*
  ^.env/
)
'''

[tool.taskipy.tasks]
test = "pytest -s -x --cov=e_collect -vv"
lint = "black --diff --color . && isort --check-only --diff ."
docs = "mkdocs serve"
startapp = "python manage.py startapp"
mkm = "python manage.py makemigrations"
mgt = "python manage.py migrate"
build_all = "python manage.py build --all"
build_force = "python manage.py build --all --force"
runserver = "python manage.py runserver"
shell = "python manage.py shell"
pre_test = "task lint"
post_test = "coverage html"
coverage = "coverage html"
core_version = "python manage.py core --version"
core_checkupdate = "python manage.py core --checkupdate"
